<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="7" time="3.495" timestamp="2024-09-14T11:01:04.088782-07:00" hostname="Seans-MBP.attlocal.net"><testcase classname="tests.cmds.test_plugin_cmd" name="test_create_plugin_command" time="0.023" /><testcase classname="tests.cmds.test_plugin_cmd" name="test_plugin_yaml_content" time="0.006" /><testcase classname="tests.cmds.test_plugin_cmd" name="test_plugin_py_content" time="0.005" /><testcase classname="tests.cmds.test_plugin_cmd" name="test_create_plugin_directory_structure" time="0.005" /><testcase classname="tests.cmds.test_plugin_cmd" name="test_create_plugin_invalid_args" time="0.002" /><testcase classname="tests.test_api" name="test_read_root" time="0.072" /><testcase classname="tests.test_bdd_plugin" name="test_generate_gherkin" time="1.127"><failure message="assert 1 == 0&#10; +  where 1 = &lt;Result SystemExit(1)&gt;.exit_code">def test_generate_gherkin():
        """Test the generation of a Gherkin feature file."""
        prompt = "As a user, I want to log in"
        result = runner.invoke(app, ["create", prompt, "--output-file", "features/test_login.feature", "--generate-code"])
    
&gt;       assert result.exit_code == 0
E       assert 1 == 0
E        +  where 1 = &lt;Result SystemExit(1)&gt;.exit_code

tests/test_bdd_plugin.py:14: AssertionError</failure></testcase></testsuite></testsuites>